export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const GET_RANDOM_JOKE = "GET_RANDOM_JOKE";
export const JOKE_LOADING = "JOKE_LOADING";

export const GET_ERRORS = "GET_ERRORS";


